# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdbb9c11ededaf934fe8a5699156b66c5f2ab01c37b71b63165a31797e37c7e0d673f492a9ca3c3db9bdc2b6ba9e4fe1e84b0ac314cb497b423a73ae515a2779

test:
  secret_key_base: 4148ed02679e4bded5e873c0ef9dc176b021401b555a2606d6543f45f4c5d4c359e5e0756cc5d9dd7b52c25e2dacd65ffdec9a7bad237990041bfb87f8dd1f61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
